### ISSUE TITLE
Is there an example of unmarshalling some XML and converting it to a to Java proto instance?

### ISSUE THREAD

**Issue by salimfadhleyhtp** [entur/schema2proto#194]
I've been able to use schema2proto to convert an XSD to a .proto file. 

Do you have an example of how I would do the following:
1. Given an xml file based on an xsd schema 
2. Take the xml string or bytes etc and use it to generate a proto file with the same content?

Background: I receive a feed of data a message bus. The messages on this feed are provided in XML. The vendor provides XML schemas. I'm trying to convert every message sent on this feed into an equivalent Protobuf message. The benefit of doing this will be smaller messages which cost less for us to store on our side. I'm looking for way to initialize a new Protobuf object from the content of the XML, preferably in a single operation.

**Comment by seime** [comment]
What you could do is to 

- generate java stubs from the xsd (ie jaxb or similar)
- generate java stubs from the proto descriptors
- use a tool like https://mapstruct.org/ to generate mapping code from xml stub to proto stub

Then you parse the xml using the xml java stubs, map them to the protobuf stubs and serialize them.

I am not aware of any tool that does this directly, but it might exist.
