### ISSUE TITLE
Failure to find org.glassfish.jaxb:xsom:jar:2.4.0-b190812-entur

### ISSUE THREAD

**Issue by netsecu** [entur/schema2proto#2]
This is ```mvn package``` error msg.

**Comment by seime** [comment]
Added note how to build this artifact;

> NOTE: This project depend on an artifact xsom-2.4.0-b190812-entur.jar . This artifact is not published to any repo (yet) but can be built from https://github.com/entur/jaxb-ri/tree/master/jaxb-ri/xsom .
