### ISSUE TITLE
Support \\ in regex options parsing

### ISSUE THREAD

**Issue by mortenlocka** [entur/schema2proto#239]
Wire strips a \ when parsing string options that are a regex. This makes the regex option invalid. 

^([A-Z]{3}):([A-Za-z]+):([0-9ÆØÅæøåA-Za-z_\\-]+)$

Gets parsed as:
^([A-Z]{3}):([A-Za-z]+):([0-9ÆØÅæøåA-Za-z_\-]+)$

**Comment by seime** [comment]
Fixed
