### ISSUE TITLE
Can you publish  xsom-2.4.0-b190812-entur.jar?

### ISSUE THREAD

**Issue by jacalata** [entur/schema2proto#4]
The README says "NOTE: This project depend on an artifact xsom-2.4.0-b190812-entur.jar . This artifact is not published to any repo (yet) ".

Since 3.0 has been published, is there still any intention to publish this 2.4 jar?

**Comment by seime** [comment]
You can deploy the artifacts found here https://github.com/entur/schema2proto/tree/develop/xsom-entur-jar in your own repo or locally. We will not invest the time to pull request these changes to the main fork.
