### ISSUE TITLE
Command line options not handled the same as the configFile.yml

### ISSUE THREAD

**Issue by drHeimskirk** [entur/schema2proto#53]
When passing the --options=cc_enable_arenas:true command line option, the code in Schema2Proto.java, parseCommandLineOptions adds everything to the options hashMap as a String.  This causes addConfigurationSpecifiedOptions to see treat the value as a string and put quotes around it when adding it to the .proto file.

Note that this behavior is different to how it is handled if the option is read in from a yml file.  The values read in from the yml file are correctly added as a Boolean type and therefore are added correctly to the .proto file.

Our problem is that the program will not allow a config file to be used when the --outputDirectory option is on the command line.  Due to the nature of the build process, the output directory does change and therefore is more convenient to put on the command line rather than generating a new config file for different configurations (which is what we do for a workaround).

I have attached some code which appears to fix the problem.  See line 398. (I don't seem to have the permissions to push a branch to create a pull request).  (extension changed to txt because it would not let me upload a .java file).

[Schema2Proto.txt](https://github.com/entur/schema2proto/files/4957179/Schema2Proto.txt)

**Comment by seime** [comment]
In order to create a pull request you must first clone the repo to your account. Go to the main project page and look for a button labeled "Fork" in your upper right corner.

**Comment by seime** [comment]
Fixed by #57
