### ISSUE TITLE
Breaks on non-URI namespaces

### ISSUE THREAD

**Issue by NielsUll** [entur/schema2proto#71]
I am trying to run it for a schema with a urn namespace like
urn:com:mycompany:myproject:mymessage:20200901:001

I get the warning 
`Unable to create decent package name from XML namespace urn:com:mycompany:myproject:mymessage:20200901:001, falling back to urn:com:mycompany:myproject:mymessage:20200901:001`
and it then fails when generating the file:

`Error generating proto files: src\main\proto\urn:com:mycompany:myproject:mymessage:20200901:001\urn:com:mycompany:myproject:mymessage:20200901:001.proto (The filename, directory name, or volume label syntax is incorrect)`

I can fix it by configuring forceProtoPackage: com.company.myproject.mymessage.x20200901.x001 but this requires manual maintenance if the namespace changes.

**Comment by seime** [comment]
Thanks,

could you provide a PR?
