### ISSUE TITLE
Remove enum name prefix from enum value

### ISSUE THREAD

**Issue by Sufaev** [entur/schema2proto#86]
What is the reason why enum name was added as prefix to enum values? Is it some technical inevitability?

On my opinion it creates mess of useless text. Especially when you start  writing application which is working with generated models.

**Comment by Sufaev** [comment]
I already found an answer - is it due to exception com.squareup.wire.schema.SchemaException: multiple enums share constant.

Could you explain me, please, why several enums in one proto file cannot have the same value?
Is it a limitation of some programing language implementation of protobuf?

**Comment by Sufaev** [comment]
Sorry for this stupid topic. I found answer here: https://github.com/square/wire/issues/678

"This is working as intended and matches protoc behavior. In C++ the constants for these values are hoisted to the enclosing message type which requires unique naming in that scope."

But it is very sad that XSD enum names will not fit PROTO :(

**Comment by seime** [comment]
The naming is also according to the official style guide https://developers.google.com/protocol-buffers/docs/style#enums
