### ISSUE TITLE
Add java_package and java_outer_classname options to proto files

### ISSUE THREAD

**Issue by Sufaev** [entur/schema2proto#88]
Currently your library converts each XSD schema file to one proto file.
One XSD schema may contain several data structures.
Usually in JAXB each data structure become a separate Java class located in the package taken from XSD.
But protobuf always wrap all internal messages in the additional wrapper Java class with the name of proto file or name specified in java_outer_classname.

As the result:
1) XSD file https://combat.vision/xsds/2017/05/12/Base.xsd become a proto file vision_combat_xsds__2017__05__12_base.proto with package vision.combat.xsds._2017._05._12.base inside.
2) But when we generate Java files using protoc it creates additional wrapper class inside the vision.combat.xsds._2017._05._12.base package. As the result we have class vision.combat.xsds._2017._05._12.base.Base.

I propose to add java_outer_classname option with the last part of packge name (the XSD schema name, e.g. "Base") and java_package option with the other part of package vision.combat.xsds._2017._05._12.
In this case it will create one package vision.combat.xsds._2017._05._12 with many Java classes inside having name of the last part of proto package name instead of one class per package with the same name as last package part name.

You can look at the file hierarchy of proto files generated based on this schema to understand what I mean.
https://combat.vision/xsds/2019/04/11/MIP-IES.xsd

**Comment by seime** [comment]
Are you actually looking for the `java_multiple_files` option? https://developers.google.com/protocol-buffers/docs/proto3

You can set it using `options` command line/config file option. (See example usage here: https://github.com/entur/netex-protobuf/blob/develop/netex_to_protobuf_config.yaml)

**Comment by Sufaev** [comment]
Probably yes. Thank you very much. Sorry that I disturb you with so stupid questions. Option java_multiple_files is even better then my proposition.

Am I correctly understand that one XSD file always converts to one Proto file and it is not possible to generate each top-level message in a separate proto file to solve possible cyclic dependencies between files? I mean it is not possible to configure multiple files on proto file level, but only on java output level?

**Comment by Sufaev** [comment]
Can we have some short discussion via any messenger or email to not flood in tracker, please.
