### ISSUE TITLE
Is there any way to process abstract attributes with this library?

### ISSUE THREAD

**Issue by Sufaev** [entur/schema2proto#89]
XSD allows to define some attribute of abstract type without internal sub-attributes.
Than another XSD file may reference abstract type in previous one and declare child structure with some specific attributes.

But proto3 does not allow to put child inplementations into parent field as there is no inheritance supported.
As the result, your library generates empty messages without attributes for abstract data structures.

Is there any option in the library to:
1) Add all child implementations of some abstract structure as its attributes?

message parent {
  Child1 child1 = 1;
  Child2 child2 = 2;
...
}

2) Add string type and byte array value into abstract structure to be able to have cascade serialization like in JSON? 
message parent {
  string class_name = 1;
  string child_serialized = 2; 
}

**Comment by seime** [comment]
`  --derivationBySubsumption <true|false>      `                                    
enable derivation by subsumption   https://cs.au.dk/~amoeller/XML/schemas/xmlschema-inheritance.html
